### ISSUE TITLE
[move-cli, evm] `move package test` fails unexpectedly

### ISSUE THREAD

**Issue by junkil-park** [diem/move#212]
To reproduce,

in `move/language/documentation/examples/experimental/basic-coin`,
add a test file to `tests/BasicCoinTest.move`:

```
module BasicCoin::BasicCoinTest {
    #[test]
    fun compare_string() {
        let s1 = b"string";
        let s2 = b"string";
        assert!(s1==s2, 0);
    }
}
```
and then,

```
$ move package build
BUILDING MoveStdlib
BUILDING BasicCoin

$ move package test
BUILDING MoveStdlib
BUILDING BasicCoin
Running Move unit tests
[ PASS    ] 0xbc::BasicCoinTest::compare_string
Test result: OK. Total tests: 1; passed: 1; failed: 0

$ move package test
CACHED MoveStdlib
BUILDING BasicCoin
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: No such file or directory './build/MoveStdlib/sources/ASCIITests.move'', language/tools/move-cli/src/package/cli.rs:514:83
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

$ RUST_BACKTRACE=1 move package test
CACHED MoveStdlib
BUILDING BasicCoin
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: No such file or directory './build/MoveStdlib/sources/ASCIITests.move'', language/tools/move-cli/src/package/cli.rs:514:83
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::result::unwrap_failed
   3: core::result::Result<T,E>::unwrap
             at /private/tmp/rust-20220304-34642-f8s218/rustc-1.59.0-src/library/core/src/result.rs:1018:23
   4: move_cli::package::cli::run_move_unit_tests::{{closure}}
             at /Users/jkpark/Work/move/language/tools/move-cli/src/package/cli.rs:514:54
   5: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut
             at /private/tmp/rust-20220304-34642-f8s218/rustc-1.59.0-src/library/core/src/ops/function.rs:269:13
   6: move_package::compilation::compiled_package::CompiledPackage::build
             at /Users/jkpark/Work/move/language/tools/move-package/src/compilation/compiled_package.rs:550:42
   7: move_package::compilation::build_plan::BuildPlan::compile_with_driver
             at /Users/jkpark/Work/move/language/tools/move-package/src/compilation/build_plan.rs:75:36
   8: move_cli::package::cli::run_move_unit_tests
             at /Users/jkpark/Work/move/language/tools/move-cli/src/package/cli.rs:510:15
   9: move_cli::package::cli::handle_package_commands
             at /Users/jkpark/Work/move/language/tools/move-cli/src/package/cli.rs:424:26
  10: move_cli::run_cli
             at /Users/jkpark/Work/move/language/tools/move-cli/src/lib.rs:116:37
  11: move_cli::move_cli
             at /Users/jkpark/Work/move/language/tools/move-cli/src/lib.rs:131:5
  12: move::main
             at /Users/jkpark/Work/move/language/tools/move-cli/src/main.rs:10:5
  13: core::ops::function::FnOnce::call_once
             at /private/tmp/rust-20220304-34642-f8s218/rustc-1.59.0-src/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

This issue is there too with the flag `--evm`. To reproduce this, in `language/evm/examples`, run `move package test`.

**Comment by tdergouzi** [comment]
I got the same error,  and i found the MoveStdlib unit test files' name is not matched with module in build.  I had to changed the unit files' name to solve the problem. Maybe it's bug of move-cli.

**Comment by junkil-park** [comment]
@tdergouzi , I believe that this issue has been fixed in the `move-cli` in the `move-language/move` repo: https://github.com/move-language/move/tree/main/language/tools/move-cli

If if there is still an issue, please feel free to open the issue again.
